services:
  - type: web
    name: hexagon
    env: node
    plan: free
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
